DECLARE
    CURSOR cursor_dep IS
    SELECT D.DEPARTMENT_NAME, (SELECT COUNT(*) FROM OEHR_EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) AS qty
    FROM OEHR_DEPARTMENTS D
    WHERE (SELECT COUNT(*) FROM OEHR_EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) > 5;

BEGIN
    FOR dep IN cursor_dep LOOP
        DBMS_OUTPUT.PUT_LINE('Nome: ' || dep.DEPARTMENT_NAME || ' | Quantidade empregados: ' || dep.qty || ' | Row Count: ' || cursor_dep%ROWCOUNT);
    END LOOP;
END;
